
server:
    port: 8080

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://dpg-d8jg22rtqb8s73c42lm0-a.oregon-postgres.render.com:5432/spacetrain?sslmode=require
    username: spacetrain_user
    password: HUdQBnmx3Pj6hd7xaBXr2LSWUq0902sS
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgresql.sql

